language: python

python:
  - 2.7

env:
  - DJANGO=1.5.5 TEST=chatserver
  - DJANGO=1.6.2 TEST=chatserver.tests

branches:
  except:
    - devel

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r examples/chatserver/tests/requirements.txt  --use-mirrors
  - python setup.py -q install

services:
  - redis-server

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
 - cd examples && ./manage.py test $TEST
