language: python

python:
  - 2.7

env:
  - DJANGO=1.5.11 MIGRATE='true'
  - DJANGO=1.6.8 MIGRATE='true'
  - DJANGO=1.7.1 MIGRATE='./manage.py migrate'

branches:
  only:
    - master

install:
  - pip install -q Django==$DJANGO
  - pip install -r examples/chatserver/tests/requirements.txt
  - python setup.py -q install

services:
  - redis-server

before_script:
  - pip freeze

script:
  - cd examples && $MIGRATE && ./manage.py test chatserver --settings=chatserver.tests.settings
