language: python

python:
  - 2.7

env:
  - DJANGO=1.5.10
  - DJANGO=1.6.7

branches:
  only:
    - master
    - echo-message

install:
  - pip install -q Django==$DJANGO
  - pip install -r examples/chatserver/tests/requirements.txt
  - python setup.py -q install

services:
  - redis-server

before_script:
  - pip freeze

script:
  - cd examples && ./manage.py test chatserver --settings=chatserver.tests.settings
