language: python

python:
  - 2.7

env:
  - DJANGO=1.5.7
  - DJANGO=1.6.4

branches:
  only:
    - master

install:
  - pip install -q Django==$DJANGO
  - pip install -r examples/chatserver/tests/requirements.txt
  - python setup.py -q install

services:
  - redis-server

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
 - cd examples && ./manage.py test chatserver --settings=chatserver.test_settings
